# =========================
# Project Metadata
# =========================
[project]
name = "Production-Grade-AI-Agentic-System"
version = "1.0.0"
description = "Building the 7 Layers of a Production Grade Agentic AI System."
authors = [{name = "Amr Abdelaty", email = "amr.abdelaty.fathallah@gmail.com"}]
readme = "README.md"
requires-python = ">=3.13"
license = {file = "LICENSE"}
keywords = ["chatbot", "ai_agentic_system"]
dependencies = [
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
]

[project.urls]
Reporistory = "https://github.com/Amr-Abdelaty-fathalla/production-grade-ai-agentic-system.git"
